//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 Stone.g 2013-02-23 21:13:45

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

namespace  Stone.Compiler 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class StoneLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__51=51;
	public const int T__52=52;
	public const int T__53=53;
	public const int T__54=54;
	public const int T__55=55;
	public const int T__56=56;
	public const int T__57=57;
	public const int T__58=58;
	public const int T__59=59;
	public const int T__60=60;
	public const int T__61=61;
	public const int T__62=62;
	public const int T__63=63;
	public const int T__64=64;
	public const int T__65=65;
	public const int T__66=66;
	public const int T__67=67;
	public const int Class_Def=4;
	public const int Class_Def_Body=5;
	public const int DEDENT=6;
	public const int DOUBLE=7;
	public const int Data_Body=8;
	public const int Data_Def=9;
	public const int Data_Def_Item=10;
	public const int EXPONENT=11;
	public const int Expr_Access=12;
	public const int Expr_Call=13;
	public const int Expr_Lambda=14;
	public const int Expr_Message=15;
	public const int Expr_New_Data=16;
	public const int Func_Args=17;
	public const int Func_Declare=18;
	public const int Func_Def=19;
	public const int INDENT=20;
	public const int INT=21;
	public const int LIDENT=22;
	public const int Lambda_Args=23;
	public const int Match_Cross=24;
	public const int Match_Var=25;
	public const int Message_Args=26;
	public const int Message_Declare=27;
	public const int Message_Def=28;
	public const int Message_Item=29;
	public const int Module_Def=30;
	public const int NEWLINE=31;
	public const int NORMAL_STRING=32;
	public const int OP_DIV=33;
	public const int OP_MINUS=34;
	public const int OP_MUL=35;
	public const int OP_PLUS=36;
	public const int Proxy_Def=37;
	public const int Proxy_Def_Body=38;
	public const int Root=39;
	public const int Stmt_Alloc=40;
	public const int Stmt_Assign=41;
	public const int Stmt_Block=42;
	public const int Stmt_Call=43;
	public const int Stmt_If=44;
	public const int Stmt_Return=45;
	public const int Type_Atom=46;
	public const int Type_Cross=47;
	public const int Type_Func=48;
	public const int UIDENT=49;
	public const int WS=50;

		int CurrentIndent = 0;

		Queue<IToken> tokens = new Queue<IToken>();

	    public override void Emit(IToken token) 
	    {
	        state.token = token;
	        tokens.Enqueue(token);
	    }
	    public override IToken NextToken()
	    {
	        base.NextToken();
	        if ( tokens.Count ==0 )
			{
				IToken token = new CommonToken(EOF, "EOF");
	            token.StartIndex = CharIndex;
	            token.StopIndex = CharIndex;
	            return token;
			}
	        return tokens.Dequeue();
	    }


    // delegates
    // delegators

	public StoneLexer()
	{
		OnCreated();
	}

	public StoneLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public StoneLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "Stone.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_Expr_Access();
	partial void LeaveRule_Expr_Access();

	// $ANTLR start "Expr_Access"
	[GrammarRule("Expr_Access")]
	private void mExpr_Access()
	{
		EnterRule_Expr_Access();
		EnterRule("Expr_Access", 1);
		TraceIn("Expr_Access", 1);
		try
		{
			int _type = Expr_Access;
			int _channel = DefaultTokenChannel;
			// Stone.g:36:13: ( '.' )
			DebugEnterAlt(1);
			// Stone.g:36:15: '.'
			{
			DebugLocation(36, 15);
			Match('.'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("Expr_Access", 1);
			LeaveRule("Expr_Access", 1);
			LeaveRule_Expr_Access();
		}
	}
	// $ANTLR end "Expr_Access"

	partial void EnterRule_OP_DIV();
	partial void LeaveRule_OP_DIV();

	// $ANTLR start "OP_DIV"
	[GrammarRule("OP_DIV")]
	private void mOP_DIV()
	{
		EnterRule_OP_DIV();
		EnterRule("OP_DIV", 2);
		TraceIn("OP_DIV", 2);
		try
		{
			int _type = OP_DIV;
			int _channel = DefaultTokenChannel;
			// Stone.g:37:8: ( '/' )
			DebugEnterAlt(1);
			// Stone.g:37:10: '/'
			{
			DebugLocation(37, 10);
			Match('/'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("OP_DIV", 2);
			LeaveRule("OP_DIV", 2);
			LeaveRule_OP_DIV();
		}
	}
	// $ANTLR end "OP_DIV"

	partial void EnterRule_OP_MINUS();
	partial void LeaveRule_OP_MINUS();

	// $ANTLR start "OP_MINUS"
	[GrammarRule("OP_MINUS")]
	private void mOP_MINUS()
	{
		EnterRule_OP_MINUS();
		EnterRule("OP_MINUS", 3);
		TraceIn("OP_MINUS", 3);
		try
		{
			int _type = OP_MINUS;
			int _channel = DefaultTokenChannel;
			// Stone.g:38:10: ( '-' )
			DebugEnterAlt(1);
			// Stone.g:38:12: '-'
			{
			DebugLocation(38, 12);
			Match('-'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("OP_MINUS", 3);
			LeaveRule("OP_MINUS", 3);
			LeaveRule_OP_MINUS();
		}
	}
	// $ANTLR end "OP_MINUS"

	partial void EnterRule_OP_MUL();
	partial void LeaveRule_OP_MUL();

	// $ANTLR start "OP_MUL"
	[GrammarRule("OP_MUL")]
	private void mOP_MUL()
	{
		EnterRule_OP_MUL();
		EnterRule("OP_MUL", 4);
		TraceIn("OP_MUL", 4);
		try
		{
			int _type = OP_MUL;
			int _channel = DefaultTokenChannel;
			// Stone.g:39:8: ( '*' )
			DebugEnterAlt(1);
			// Stone.g:39:10: '*'
			{
			DebugLocation(39, 10);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("OP_MUL", 4);
			LeaveRule("OP_MUL", 4);
			LeaveRule_OP_MUL();
		}
	}
	// $ANTLR end "OP_MUL"

	partial void EnterRule_OP_PLUS();
	partial void LeaveRule_OP_PLUS();

	// $ANTLR start "OP_PLUS"
	[GrammarRule("OP_PLUS")]
	private void mOP_PLUS()
	{
		EnterRule_OP_PLUS();
		EnterRule("OP_PLUS", 5);
		TraceIn("OP_PLUS", 5);
		try
		{
			int _type = OP_PLUS;
			int _channel = DefaultTokenChannel;
			// Stone.g:40:9: ( '+' )
			DebugEnterAlt(1);
			// Stone.g:40:11: '+'
			{
			DebugLocation(40, 11);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("OP_PLUS", 5);
			LeaveRule("OP_PLUS", 5);
			LeaveRule_OP_PLUS();
		}
	}
	// $ANTLR end "OP_PLUS"

	partial void EnterRule_T__51();
	partial void LeaveRule_T__51();

	// $ANTLR start "T__51"
	[GrammarRule("T__51")]
	private void mT__51()
	{
		EnterRule_T__51();
		EnterRule("T__51", 6);
		TraceIn("T__51", 6);
		try
		{
			int _type = T__51;
			int _channel = DefaultTokenChannel;
			// Stone.g:41:7: ( '(' )
			DebugEnterAlt(1);
			// Stone.g:41:9: '('
			{
			DebugLocation(41, 9);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__51", 6);
			LeaveRule("T__51", 6);
			LeaveRule_T__51();
		}
	}
	// $ANTLR end "T__51"

	partial void EnterRule_T__52();
	partial void LeaveRule_T__52();

	// $ANTLR start "T__52"
	[GrammarRule("T__52")]
	private void mT__52()
	{
		EnterRule_T__52();
		EnterRule("T__52", 7);
		TraceIn("T__52", 7);
		try
		{
			int _type = T__52;
			int _channel = DefaultTokenChannel;
			// Stone.g:42:7: ( ')' )
			DebugEnterAlt(1);
			// Stone.g:42:9: ')'
			{
			DebugLocation(42, 9);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__52", 7);
			LeaveRule("T__52", 7);
			LeaveRule_T__52();
		}
	}
	// $ANTLR end "T__52"

	partial void EnterRule_T__53();
	partial void LeaveRule_T__53();

	// $ANTLR start "T__53"
	[GrammarRule("T__53")]
	private void mT__53()
	{
		EnterRule_T__53();
		EnterRule("T__53", 8);
		TraceIn("T__53", 8);
		try
		{
			int _type = T__53;
			int _channel = DefaultTokenChannel;
			// Stone.g:43:7: ( ',' )
			DebugEnterAlt(1);
			// Stone.g:43:9: ','
			{
			DebugLocation(43, 9);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__53", 8);
			LeaveRule("T__53", 8);
			LeaveRule_T__53();
		}
	}
	// $ANTLR end "T__53"

	partial void EnterRule_T__54();
	partial void LeaveRule_T__54();

	// $ANTLR start "T__54"
	[GrammarRule("T__54")]
	private void mT__54()
	{
		EnterRule_T__54();
		EnterRule("T__54", 9);
		TraceIn("T__54", 9);
		try
		{
			int _type = T__54;
			int _channel = DefaultTokenChannel;
			// Stone.g:44:7: ( '->' )
			DebugEnterAlt(1);
			// Stone.g:44:9: '->'
			{
			DebugLocation(44, 9);
			Match("->"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__54", 9);
			LeaveRule("T__54", 9);
			LeaveRule_T__54();
		}
	}
	// $ANTLR end "T__54"

	partial void EnterRule_T__55();
	partial void LeaveRule_T__55();

	// $ANTLR start "T__55"
	[GrammarRule("T__55")]
	private void mT__55()
	{
		EnterRule_T__55();
		EnterRule("T__55", 10);
		TraceIn("T__55", 10);
		try
		{
			int _type = T__55;
			int _channel = DefaultTokenChannel;
			// Stone.g:45:7: ( ':' )
			DebugEnterAlt(1);
			// Stone.g:45:9: ':'
			{
			DebugLocation(45, 9);
			Match(':'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__55", 10);
			LeaveRule("T__55", 10);
			LeaveRule_T__55();
		}
	}
	// $ANTLR end "T__55"

	partial void EnterRule_T__56();
	partial void LeaveRule_T__56();

	// $ANTLR start "T__56"
	[GrammarRule("T__56")]
	private void mT__56()
	{
		EnterRule_T__56();
		EnterRule("T__56", 11);
		TraceIn("T__56", 11);
		try
		{
			int _type = T__56;
			int _channel = DefaultTokenChannel;
			// Stone.g:46:7: ( '::' )
			DebugEnterAlt(1);
			// Stone.g:46:9: '::'
			{
			DebugLocation(46, 9);
			Match("::"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__56", 11);
			LeaveRule("T__56", 11);
			LeaveRule_T__56();
		}
	}
	// $ANTLR end "T__56"

	partial void EnterRule_T__57();
	partial void LeaveRule_T__57();

	// $ANTLR start "T__57"
	[GrammarRule("T__57")]
	private void mT__57()
	{
		EnterRule_T__57();
		EnterRule("T__57", 12);
		TraceIn("T__57", 12);
		try
		{
			int _type = T__57;
			int _channel = DefaultTokenChannel;
			// Stone.g:47:7: ( '=' )
			DebugEnterAlt(1);
			// Stone.g:47:9: '='
			{
			DebugLocation(47, 9);
			Match('='); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__57", 12);
			LeaveRule("T__57", 12);
			LeaveRule_T__57();
		}
	}
	// $ANTLR end "T__57"

	partial void EnterRule_T__58();
	partial void LeaveRule_T__58();

	// $ANTLR start "T__58"
	[GrammarRule("T__58")]
	private void mT__58()
	{
		EnterRule_T__58();
		EnterRule("T__58", 13);
		TraceIn("T__58", 13);
		try
		{
			int _type = T__58;
			int _channel = DefaultTokenChannel;
			// Stone.g:48:7: ( '=>' )
			DebugEnterAlt(1);
			// Stone.g:48:9: '=>'
			{
			DebugLocation(48, 9);
			Match("=>"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__58", 13);
			LeaveRule("T__58", 13);
			LeaveRule_T__58();
		}
	}
	// $ANTLR end "T__58"

	partial void EnterRule_T__59();
	partial void LeaveRule_T__59();

	// $ANTLR start "T__59"
	[GrammarRule("T__59")]
	private void mT__59()
	{
		EnterRule_T__59();
		EnterRule("T__59", 14);
		TraceIn("T__59", 14);
		try
		{
			int _type = T__59;
			int _channel = DefaultTokenChannel;
			// Stone.g:49:7: ( 'class' )
			DebugEnterAlt(1);
			// Stone.g:49:9: 'class'
			{
			DebugLocation(49, 9);
			Match("class"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__59", 14);
			LeaveRule("T__59", 14);
			LeaveRule_T__59();
		}
	}
	// $ANTLR end "T__59"

	partial void EnterRule_T__60();
	partial void LeaveRule_T__60();

	// $ANTLR start "T__60"
	[GrammarRule("T__60")]
	private void mT__60()
	{
		EnterRule_T__60();
		EnterRule("T__60", 15);
		TraceIn("T__60", 15);
		try
		{
			int _type = T__60;
			int _channel = DefaultTokenChannel;
			// Stone.g:50:7: ( 'data' )
			DebugEnterAlt(1);
			// Stone.g:50:9: 'data'
			{
			DebugLocation(50, 9);
			Match("data"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__60", 15);
			LeaveRule("T__60", 15);
			LeaveRule_T__60();
		}
	}
	// $ANTLR end "T__60"

	partial void EnterRule_T__61();
	partial void LeaveRule_T__61();

	// $ANTLR start "T__61"
	[GrammarRule("T__61")]
	private void mT__61()
	{
		EnterRule_T__61();
		EnterRule("T__61", 16);
		TraceIn("T__61", 16);
		try
		{
			int _type = T__61;
			int _channel = DefaultTokenChannel;
			// Stone.g:51:7: ( 'if' )
			DebugEnterAlt(1);
			// Stone.g:51:9: 'if'
			{
			DebugLocation(51, 9);
			Match("if"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__61", 16);
			LeaveRule("T__61", 16);
			LeaveRule_T__61();
		}
	}
	// $ANTLR end "T__61"

	partial void EnterRule_T__62();
	partial void LeaveRule_T__62();

	// $ANTLR start "T__62"
	[GrammarRule("T__62")]
	private void mT__62()
	{
		EnterRule_T__62();
		EnterRule("T__62", 17);
		TraceIn("T__62", 17);
		try
		{
			int _type = T__62;
			int _channel = DefaultTokenChannel;
			// Stone.g:52:7: ( 'module' )
			DebugEnterAlt(1);
			// Stone.g:52:9: 'module'
			{
			DebugLocation(52, 9);
			Match("module"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__62", 17);
			LeaveRule("T__62", 17);
			LeaveRule_T__62();
		}
	}
	// $ANTLR end "T__62"

	partial void EnterRule_T__63();
	partial void LeaveRule_T__63();

	// $ANTLR start "T__63"
	[GrammarRule("T__63")]
	private void mT__63()
	{
		EnterRule_T__63();
		EnterRule("T__63", 18);
		TraceIn("T__63", 18);
		try
		{
			int _type = T__63;
			int _channel = DefaultTokenChannel;
			// Stone.g:53:7: ( 'proxy' )
			DebugEnterAlt(1);
			// Stone.g:53:9: 'proxy'
			{
			DebugLocation(53, 9);
			Match("proxy"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__63", 18);
			LeaveRule("T__63", 18);
			LeaveRule_T__63();
		}
	}
	// $ANTLR end "T__63"

	partial void EnterRule_T__64();
	partial void LeaveRule_T__64();

	// $ANTLR start "T__64"
	[GrammarRule("T__64")]
	private void mT__64()
	{
		EnterRule_T__64();
		EnterRule("T__64", 19);
		TraceIn("T__64", 19);
		try
		{
			int _type = T__64;
			int _channel = DefaultTokenChannel;
			// Stone.g:54:7: ( 'return' )
			DebugEnterAlt(1);
			// Stone.g:54:9: 'return'
			{
			DebugLocation(54, 9);
			Match("return"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__64", 19);
			LeaveRule("T__64", 19);
			LeaveRule_T__64();
		}
	}
	// $ANTLR end "T__64"

	partial void EnterRule_T__65();
	partial void LeaveRule_T__65();

	// $ANTLR start "T__65"
	[GrammarRule("T__65")]
	private void mT__65()
	{
		EnterRule_T__65();
		EnterRule("T__65", 20);
		TraceIn("T__65", 20);
		try
		{
			int _type = T__65;
			int _channel = DefaultTokenChannel;
			// Stone.g:55:7: ( '|' )
			DebugEnterAlt(1);
			// Stone.g:55:9: '|'
			{
			DebugLocation(55, 9);
			Match('|'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__65", 20);
			LeaveRule("T__65", 20);
			LeaveRule_T__65();
		}
	}
	// $ANTLR end "T__65"

	partial void EnterRule_T__66();
	partial void LeaveRule_T__66();

	// $ANTLR start "T__66"
	[GrammarRule("T__66")]
	private void mT__66()
	{
		EnterRule_T__66();
		EnterRule("T__66", 21);
		TraceIn("T__66", 21);
		try
		{
			int _type = T__66;
			int _channel = DefaultTokenChannel;
			// Stone.g:56:7: ( '¡Á' )
			DebugEnterAlt(1);
			// Stone.g:56:9: '¡Á'
			{
			DebugLocation(56, 9);
			Match('\u00D7'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__66", 21);
			LeaveRule("T__66", 21);
			LeaveRule_T__66();
		}
	}
	// $ANTLR end "T__66"

	partial void EnterRule_T__67();
	partial void LeaveRule_T__67();

	// $ANTLR start "T__67"
	[GrammarRule("T__67")]
	private void mT__67()
	{
		EnterRule_T__67();
		EnterRule("T__67", 22);
		TraceIn("T__67", 22);
		try
		{
			int _type = T__67;
			int _channel = DefaultTokenChannel;
			// Stone.g:57:7: ( '¦Ë' )
			DebugEnterAlt(1);
			// Stone.g:57:9: '¦Ë'
			{
			DebugLocation(57, 9);
			Match('\u03BB'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__67", 22);
			LeaveRule("T__67", 22);
			LeaveRule_T__67();
		}
	}
	// $ANTLR end "T__67"

	partial void EnterRule_NEWLINE();
	partial void LeaveRule_NEWLINE();

	// $ANTLR start "NEWLINE"
	[GrammarRule("NEWLINE")]
	private void mNEWLINE()
	{
		EnterRule_NEWLINE();
		EnterRule("NEWLINE", 23);
		TraceIn("NEWLINE", 23);
		try
		{
			int _type = NEWLINE;
			int _channel = DefaultTokenChannel;
			// Stone.g:320:3: ( ( '\\n' )+ ( ' ' | '\\t' )* )
			DebugEnterAlt(1);
			// Stone.g:320:3: ( '\\n' )+ ( ' ' | '\\t' )*
			{
			DebugLocation(320, 3);
			// Stone.g:320:3: ( '\\n' )+
			int cnt1=0;
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_0 = input.LA(1);

				if ((LA1_0=='\n'))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch (alt1)
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:320:3: '\\n'
					{
					DebugLocation(320, 3);
					Match('\n'); 

					}
					break;

				default:
					if (cnt1 >= 1)
						goto loop1;

					EarlyExitException eee1 = new EarlyExitException( 1, input );
					DebugRecognitionException(eee1);
					throw eee1;
				}
				cnt1++;
			}
			loop1:
				;

			} finally { DebugExitSubRule(1); }

			DebugLocation(320, 9);
			// Stone.g:320:9: ( ' ' | '\\t' )*
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, false);
				int LA2_0 = input.LA(1);

				if ((LA2_0=='\t'||LA2_0==' '))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch ( alt2 )
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:
					{
					DebugLocation(320, 9);
					input.Consume();


					}
					break;

				default:
					goto loop2;
				}
			}

			loop2:
				;

			} finally { DebugExitSubRule(2); }

			DebugLocation(321, 1);

			       int indent = Text.Length;
				   while (indent != 0 && Text[Text.Length - indent] == '\n') indent--;
				   IToken token_newline = new CommonToken(NEWLINE, "NEWLINE");
				   token_newline.StartIndex = CharIndex;
				   token_newline.StopIndex = CharIndex;
				   Emit(token_newline);
			       if (indent > CurrentIndent)
			       {
				          for (int i = 0; i < indent - CurrentIndent; i++)
						  {
							IToken token = new CommonToken(INDENT, "INDENT -- " + indent);
							token.StartIndex = CharIndex;
							token.StopIndex = CharIndex;
			                Emit(token);
						  }
			       }
			       else if (indent < CurrentIndent)
			       {
			              for (int i=0; i < CurrentIndent - indent; i++)
			              {
							IToken token = new CommonToken(DEDENT, "DEDENT -- " + CurrentIndent);
							token.StartIndex = CharIndex;
							token.StopIndex = CharIndex;
			                Emit(token);
			              }
			       }
			       else
			       {
			       }
			       CurrentIndent = indent;


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NEWLINE", 23);
			LeaveRule("NEWLINE", 23);
			LeaveRule_NEWLINE();
		}
	}
	// $ANTLR end "NEWLINE"

	partial void EnterRule_LIDENT();
	partial void LeaveRule_LIDENT();

	// $ANTLR start "LIDENT"
	[GrammarRule("LIDENT")]
	private void mLIDENT()
	{
		EnterRule_LIDENT();
		EnterRule("LIDENT", 24);
		TraceIn("LIDENT", 24);
		try
		{
			int _type = LIDENT;
			int _channel = DefaultTokenChannel;
			// Stone.g:355:7: ( ( ( 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* '.' )* ( 'a' .. 'z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* ( '0' .. '9' )* )
			DebugEnterAlt(1);
			// Stone.g:355:9: ( ( 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* '.' )* ( 'a' .. 'z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* ( '0' .. '9' )*
			{
			DebugLocation(355, 9);
			// Stone.g:355:9: ( ( 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* '.' )*
			try { DebugEnterSubRule(4);
			while (true)
			{
				int alt4=2;
				try { DebugEnterDecision(4, false);
				int LA4_0 = input.LA(1);

				if (((LA4_0>='A' && LA4_0<='Z')))
				{
					alt4 = 1;
				}


				} finally { DebugExitDecision(4); }
				switch ( alt4 )
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:355:10: ( 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* '.'
					{
					DebugLocation(355, 10);
					input.Consume();

					DebugLocation(355, 21);
					// Stone.g:355:21: ( 'a' .. 'z' | 'A' .. 'Z' )*
					try { DebugEnterSubRule(3);
					while (true)
					{
						int alt3=2;
						try { DebugEnterDecision(3, false);
						int LA3_0 = input.LA(1);

						if (((LA3_0>='A' && LA3_0<='Z')||(LA3_0>='a' && LA3_0<='z')))
						{
							alt3 = 1;
						}


						} finally { DebugExitDecision(3); }
						switch ( alt3 )
						{
						case 1:
							DebugEnterAlt(1);
							// Stone.g:
							{
							DebugLocation(355, 21);
							input.Consume();


							}
							break;

						default:
							goto loop3;
						}
					}

					loop3:
						;

					} finally { DebugExitSubRule(3); }

					DebugLocation(355, 44);
					Match('.'); 

					}
					break;

				default:
					goto loop4;
				}
			}

			loop4:
				;

			} finally { DebugExitSubRule(4); }

			DebugLocation(355, 50);
			if ((input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(355, 61);
			// Stone.g:355:61: ( 'a' .. 'z' | 'A' .. 'Z' )*
			try { DebugEnterSubRule(5);
			while (true)
			{
				int alt5=2;
				try { DebugEnterDecision(5, false);
				int LA5_0 = input.LA(1);

				if (((LA5_0>='A' && LA5_0<='Z')||(LA5_0>='a' && LA5_0<='z')))
				{
					alt5 = 1;
				}


				} finally { DebugExitDecision(5); }
				switch ( alt5 )
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:
					{
					DebugLocation(355, 61);
					input.Consume();


					}
					break;

				default:
					goto loop5;
				}
			}

			loop5:
				;

			} finally { DebugExitSubRule(5); }

			DebugLocation(355, 84);
			// Stone.g:355:84: ( '0' .. '9' )*
			try { DebugEnterSubRule(6);
			while (true)
			{
				int alt6=2;
				try { DebugEnterDecision(6, false);
				int LA6_0 = input.LA(1);

				if (((LA6_0>='0' && LA6_0<='9')))
				{
					alt6 = 1;
				}


				} finally { DebugExitDecision(6); }
				switch ( alt6 )
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:
					{
					DebugLocation(355, 84);
					input.Consume();


					}
					break;

				default:
					goto loop6;
				}
			}

			loop6:
				;

			} finally { DebugExitSubRule(6); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LIDENT", 24);
			LeaveRule("LIDENT", 24);
			LeaveRule_LIDENT();
		}
	}
	// $ANTLR end "LIDENT"

	partial void EnterRule_UIDENT();
	partial void LeaveRule_UIDENT();

	// $ANTLR start "UIDENT"
	[GrammarRule("UIDENT")]
	private void mUIDENT()
	{
		EnterRule_UIDENT();
		EnterRule("UIDENT", 25);
		TraceIn("UIDENT", 25);
		try
		{
			int _type = UIDENT;
			int _channel = DefaultTokenChannel;
			// Stone.g:356:7: ( ( ( 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* '.' )* ( 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* ( '0' .. '9' )* )
			DebugEnterAlt(1);
			// Stone.g:356:9: ( ( 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* '.' )* ( 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* ( '0' .. '9' )*
			{
			DebugLocation(356, 9);
			// Stone.g:356:9: ( ( 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* '.' )*
			try { DebugEnterSubRule(8);
			while (true)
			{
				int alt8=2;
				try { DebugEnterDecision(8, false);
				try
				{
					alt8 = dfa8.Predict(input);
				}
				catch (NoViableAltException nvae)
				{
					DebugRecognitionException(nvae);
					throw;
				}
				} finally { DebugExitDecision(8); }
				switch ( alt8 )
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:356:10: ( 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* '.'
					{
					DebugLocation(356, 10);
					input.Consume();

					DebugLocation(356, 21);
					// Stone.g:356:21: ( 'a' .. 'z' | 'A' .. 'Z' )*
					try { DebugEnterSubRule(7);
					while (true)
					{
						int alt7=2;
						try { DebugEnterDecision(7, false);
						int LA7_0 = input.LA(1);

						if (((LA7_0>='A' && LA7_0<='Z')||(LA7_0>='a' && LA7_0<='z')))
						{
							alt7 = 1;
						}


						} finally { DebugExitDecision(7); }
						switch ( alt7 )
						{
						case 1:
							DebugEnterAlt(1);
							// Stone.g:
							{
							DebugLocation(356, 21);
							input.Consume();


							}
							break;

						default:
							goto loop7;
						}
					}

					loop7:
						;

					} finally { DebugExitSubRule(7); }

					DebugLocation(356, 44);
					Match('.'); 

					}
					break;

				default:
					goto loop8;
				}
			}

			loop8:
				;

			} finally { DebugExitSubRule(8); }

			DebugLocation(356, 50);
			if ((input.LA(1)>='A' && input.LA(1)<='Z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(356, 61);
			// Stone.g:356:61: ( 'a' .. 'z' | 'A' .. 'Z' )*
			try { DebugEnterSubRule(9);
			while (true)
			{
				int alt9=2;
				try { DebugEnterDecision(9, false);
				int LA9_0 = input.LA(1);

				if (((LA9_0>='A' && LA9_0<='Z')||(LA9_0>='a' && LA9_0<='z')))
				{
					alt9 = 1;
				}


				} finally { DebugExitDecision(9); }
				switch ( alt9 )
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:
					{
					DebugLocation(356, 61);
					input.Consume();


					}
					break;

				default:
					goto loop9;
				}
			}

			loop9:
				;

			} finally { DebugExitSubRule(9); }

			DebugLocation(356, 84);
			// Stone.g:356:84: ( '0' .. '9' )*
			try { DebugEnterSubRule(10);
			while (true)
			{
				int alt10=2;
				try { DebugEnterDecision(10, false);
				int LA10_0 = input.LA(1);

				if (((LA10_0>='0' && LA10_0<='9')))
				{
					alt10 = 1;
				}


				} finally { DebugExitDecision(10); }
				switch ( alt10 )
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:
					{
					DebugLocation(356, 84);
					input.Consume();


					}
					break;

				default:
					goto loop10;
				}
			}

			loop10:
				;

			} finally { DebugExitSubRule(10); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("UIDENT", 25);
			LeaveRule("UIDENT", 25);
			LeaveRule_UIDENT();
		}
	}
	// $ANTLR end "UIDENT"

	partial void EnterRule_NORMAL_STRING();
	partial void LeaveRule_NORMAL_STRING();

	// $ANTLR start "NORMAL_STRING"
	[GrammarRule("NORMAL_STRING")]
	private void mNORMAL_STRING()
	{
		EnterRule_NORMAL_STRING();
		EnterRule("NORMAL_STRING", 26);
		TraceIn("NORMAL_STRING", 26);
		try
		{
			int _type = NORMAL_STRING;
			int _channel = DefaultTokenChannel;
			// Stone.g:360:2: ( '\"' (~ '\"' )* '\"' | '\\'' (~ '\\'' )* '\\'' )
			int alt13=2;
			try { DebugEnterDecision(13, false);
			int LA13_0 = input.LA(1);

			if ((LA13_0=='\"'))
			{
				alt13 = 1;
			}
			else if ((LA13_0=='\''))
			{
				alt13 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 13, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(13); }
			switch (alt13)
			{
			case 1:
				DebugEnterAlt(1);
				// Stone.g:360:4: '\"' (~ '\"' )* '\"'
				{
				DebugLocation(360, 4);
				Match('\"'); 
				DebugLocation(360, 8);
				// Stone.g:360:8: (~ '\"' )*
				try { DebugEnterSubRule(11);
				while (true)
				{
					int alt11=2;
					try { DebugEnterDecision(11, false);
					int LA11_0 = input.LA(1);

					if (((LA11_0>='\u0000' && LA11_0<='!')||(LA11_0>='#' && LA11_0<='\uFFFF')))
					{
						alt11 = 1;
					}


					} finally { DebugExitDecision(11); }
					switch ( alt11 )
					{
					case 1:
						DebugEnterAlt(1);
						// Stone.g:
						{
						DebugLocation(360, 8);
						input.Consume();


						}
						break;

					default:
						goto loop11;
					}
				}

				loop11:
					;

				} finally { DebugExitSubRule(11); }

				DebugLocation(360, 16);
				Match('\"'); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// Stone.g:361:4: '\\'' (~ '\\'' )* '\\''
				{
				DebugLocation(361, 4);
				Match('\''); 
				DebugLocation(361, 9);
				// Stone.g:361:9: (~ '\\'' )*
				try { DebugEnterSubRule(12);
				while (true)
				{
					int alt12=2;
					try { DebugEnterDecision(12, false);
					int LA12_0 = input.LA(1);

					if (((LA12_0>='\u0000' && LA12_0<='&')||(LA12_0>='(' && LA12_0<='\uFFFF')))
					{
						alt12 = 1;
					}


					} finally { DebugExitDecision(12); }
					switch ( alt12 )
					{
					case 1:
						DebugEnterAlt(1);
						// Stone.g:
						{
						DebugLocation(361, 9);
						input.Consume();


						}
						break;

					default:
						goto loop12;
					}
				}

				loop12:
					;

				} finally { DebugExitSubRule(12); }

				DebugLocation(361, 18);
				Match('\''); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NORMAL_STRING", 26);
			LeaveRule("NORMAL_STRING", 26);
			LeaveRule_NORMAL_STRING();
		}
	}
	// $ANTLR end "NORMAL_STRING"

	partial void EnterRule_INT();
	partial void LeaveRule_INT();

	// $ANTLR start "INT"
	[GrammarRule("INT")]
	private void mINT()
	{
		EnterRule_INT();
		EnterRule("INT", 27);
		TraceIn("INT", 27);
		try
		{
			int _type = INT;
			int _channel = DefaultTokenChannel;
			// Stone.g:365:7: ( ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// Stone.g:365:9: ( '0' .. '9' )+
			{
			DebugLocation(365, 9);
			// Stone.g:365:9: ( '0' .. '9' )+
			int cnt14=0;
			try { DebugEnterSubRule(14);
			while (true)
			{
				int alt14=2;
				try { DebugEnterDecision(14, false);
				int LA14_0 = input.LA(1);

				if (((LA14_0>='0' && LA14_0<='9')))
				{
					alt14 = 1;
				}


				} finally { DebugExitDecision(14); }
				switch (alt14)
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:
					{
					DebugLocation(365, 9);
					input.Consume();


					}
					break;

				default:
					if (cnt14 >= 1)
						goto loop14;

					EarlyExitException eee14 = new EarlyExitException( 14, input );
					DebugRecognitionException(eee14);
					throw eee14;
				}
				cnt14++;
			}
			loop14:
				;

			} finally { DebugExitSubRule(14); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INT", 27);
			LeaveRule("INT", 27);
			LeaveRule_INT();
		}
	}
	// $ANTLR end "INT"

	partial void EnterRule_DOUBLE();
	partial void LeaveRule_DOUBLE();

	// $ANTLR start "DOUBLE"
	[GrammarRule("DOUBLE")]
	private void mDOUBLE()
	{
		EnterRule_DOUBLE();
		EnterRule("DOUBLE", 28);
		TraceIn("DOUBLE", 28);
		try
		{
			int _type = DOUBLE;
			int _channel = DefaultTokenChannel;
			// Stone.g:369:5: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT )
			int alt21=3;
			try { DebugEnterDecision(21, false);
			try
			{
				alt21 = dfa21.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(21); }
			switch (alt21)
			{
			case 1:
				DebugEnterAlt(1);
				// Stone.g:369:7: ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )?
				{
				DebugLocation(369, 7);
				// Stone.g:369:7: ( '0' .. '9' )+
				int cnt15=0;
				try { DebugEnterSubRule(15);
				while (true)
				{
					int alt15=2;
					try { DebugEnterDecision(15, false);
					int LA15_0 = input.LA(1);

					if (((LA15_0>='0' && LA15_0<='9')))
					{
						alt15 = 1;
					}


					} finally { DebugExitDecision(15); }
					switch (alt15)
					{
					case 1:
						DebugEnterAlt(1);
						// Stone.g:
						{
						DebugLocation(369, 7);
						input.Consume();


						}
						break;

					default:
						if (cnt15 >= 1)
							goto loop15;

						EarlyExitException eee15 = new EarlyExitException( 15, input );
						DebugRecognitionException(eee15);
						throw eee15;
					}
					cnt15++;
				}
				loop15:
					;

				} finally { DebugExitSubRule(15); }

				DebugLocation(369, 19);
				Match('.'); 
				DebugLocation(369, 23);
				// Stone.g:369:23: ( '0' .. '9' )*
				try { DebugEnterSubRule(16);
				while (true)
				{
					int alt16=2;
					try { DebugEnterDecision(16, false);
					int LA16_0 = input.LA(1);

					if (((LA16_0>='0' && LA16_0<='9')))
					{
						alt16 = 1;
					}


					} finally { DebugExitDecision(16); }
					switch ( alt16 )
					{
					case 1:
						DebugEnterAlt(1);
						// Stone.g:
						{
						DebugLocation(369, 23);
						input.Consume();


						}
						break;

					default:
						goto loop16;
					}
				}

				loop16:
					;

				} finally { DebugExitSubRule(16); }

				DebugLocation(369, 35);
				// Stone.g:369:35: ( EXPONENT )?
				int alt17=2;
				try { DebugEnterSubRule(17);
				try { DebugEnterDecision(17, false);
				int LA17_0 = input.LA(1);

				if ((LA17_0=='E'||LA17_0=='e'))
				{
					alt17 = 1;
				}
				} finally { DebugExitDecision(17); }
				switch (alt17)
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:369:35: EXPONENT
					{
					DebugLocation(369, 35);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(17); }


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// Stone.g:370:7: '.' ( '0' .. '9' )+ ( EXPONENT )?
				{
				DebugLocation(370, 7);
				Match('.'); 
				DebugLocation(370, 11);
				// Stone.g:370:11: ( '0' .. '9' )+
				int cnt18=0;
				try { DebugEnterSubRule(18);
				while (true)
				{
					int alt18=2;
					try { DebugEnterDecision(18, false);
					int LA18_0 = input.LA(1);

					if (((LA18_0>='0' && LA18_0<='9')))
					{
						alt18 = 1;
					}


					} finally { DebugExitDecision(18); }
					switch (alt18)
					{
					case 1:
						DebugEnterAlt(1);
						// Stone.g:
						{
						DebugLocation(370, 11);
						input.Consume();


						}
						break;

					default:
						if (cnt18 >= 1)
							goto loop18;

						EarlyExitException eee18 = new EarlyExitException( 18, input );
						DebugRecognitionException(eee18);
						throw eee18;
					}
					cnt18++;
				}
				loop18:
					;

				} finally { DebugExitSubRule(18); }

				DebugLocation(370, 23);
				// Stone.g:370:23: ( EXPONENT )?
				int alt19=2;
				try { DebugEnterSubRule(19);
				try { DebugEnterDecision(19, false);
				int LA19_0 = input.LA(1);

				if ((LA19_0=='E'||LA19_0=='e'))
				{
					alt19 = 1;
				}
				} finally { DebugExitDecision(19); }
				switch (alt19)
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:370:23: EXPONENT
					{
					DebugLocation(370, 23);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(19); }


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// Stone.g:371:7: ( '0' .. '9' )+ EXPONENT
				{
				DebugLocation(371, 7);
				// Stone.g:371:7: ( '0' .. '9' )+
				int cnt20=0;
				try { DebugEnterSubRule(20);
				while (true)
				{
					int alt20=2;
					try { DebugEnterDecision(20, false);
					int LA20_0 = input.LA(1);

					if (((LA20_0>='0' && LA20_0<='9')))
					{
						alt20 = 1;
					}


					} finally { DebugExitDecision(20); }
					switch (alt20)
					{
					case 1:
						DebugEnterAlt(1);
						// Stone.g:
						{
						DebugLocation(371, 7);
						input.Consume();


						}
						break;

					default:
						if (cnt20 >= 1)
							goto loop20;

						EarlyExitException eee20 = new EarlyExitException( 20, input );
						DebugRecognitionException(eee20);
						throw eee20;
					}
					cnt20++;
				}
				loop20:
					;

				} finally { DebugExitSubRule(20); }

				DebugLocation(371, 19);
				mEXPONENT(); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DOUBLE", 28);
			LeaveRule("DOUBLE", 28);
			LeaveRule_DOUBLE();
		}
	}
	// $ANTLR end "DOUBLE"

	partial void EnterRule_EXPONENT();
	partial void LeaveRule_EXPONENT();

	// $ANTLR start "EXPONENT"
	[GrammarRule("EXPONENT")]
	private void mEXPONENT()
	{
		EnterRule_EXPONENT();
		EnterRule("EXPONENT", 29);
		TraceIn("EXPONENT", 29);
		try
		{
			// Stone.g:377:10: ( ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// Stone.g:378:5: ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+
			{
			DebugLocation(378, 5);
			if (input.LA(1)=='E'||input.LA(1)=='e')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(378, 15);
			// Stone.g:378:15: ( '+' | '-' )?
			int alt22=2;
			try { DebugEnterSubRule(22);
			try { DebugEnterDecision(22, false);
			int LA22_0 = input.LA(1);

			if ((LA22_0=='+'||LA22_0=='-'))
			{
				alt22 = 1;
			}
			} finally { DebugExitDecision(22); }
			switch (alt22)
			{
			case 1:
				DebugEnterAlt(1);
				// Stone.g:
				{
				DebugLocation(378, 15);
				input.Consume();


				}
				break;

			}
			} finally { DebugExitSubRule(22); }

			DebugLocation(378, 26);
			// Stone.g:378:26: ( '0' .. '9' )+
			int cnt23=0;
			try { DebugEnterSubRule(23);
			while (true)
			{
				int alt23=2;
				try { DebugEnterDecision(23, false);
				int LA23_0 = input.LA(1);

				if (((LA23_0>='0' && LA23_0<='9')))
				{
					alt23 = 1;
				}


				} finally { DebugExitDecision(23); }
				switch (alt23)
				{
				case 1:
					DebugEnterAlt(1);
					// Stone.g:
					{
					DebugLocation(378, 26);
					input.Consume();


					}
					break;

				default:
					if (cnt23 >= 1)
						goto loop23;

					EarlyExitException eee23 = new EarlyExitException( 23, input );
					DebugRecognitionException(eee23);
					throw eee23;
				}
				cnt23++;
			}
			loop23:
				;

			} finally { DebugExitSubRule(23); }


			}

		}
		finally
		{
			TraceOut("EXPONENT", 29);
			LeaveRule("EXPONENT", 29);
			LeaveRule_EXPONENT();
		}
	}
	// $ANTLR end "EXPONENT"

	partial void EnterRule_INDENT();
	partial void LeaveRule_INDENT();

	// $ANTLR start "INDENT"
	[GrammarRule("INDENT")]
	private void mINDENT()
	{
		EnterRule_INDENT();
		EnterRule("INDENT", 30);
		TraceIn("INDENT", 30);
		try
		{
			int _type = INDENT;
			int _channel = DefaultTokenChannel;
			// Stone.g:380:7: ( 'nothing_will_match_this_indent' )
			DebugEnterAlt(1);
			// Stone.g:380:9: 'nothing_will_match_this_indent'
			{
			DebugLocation(380, 9);
			Match("nothing_will_match_this_indent"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INDENT", 30);
			LeaveRule("INDENT", 30);
			LeaveRule_INDENT();
		}
	}
	// $ANTLR end "INDENT"

	partial void EnterRule_DEDENT();
	partial void LeaveRule_DEDENT();

	// $ANTLR start "DEDENT"
	[GrammarRule("DEDENT")]
	private void mDEDENT()
	{
		EnterRule_DEDENT();
		EnterRule("DEDENT", 31);
		TraceIn("DEDENT", 31);
		try
		{
			int _type = DEDENT;
			int _channel = DefaultTokenChannel;
			// Stone.g:381:7: ( 'nothing_will_match_this_dedent' )
			DebugEnterAlt(1);
			// Stone.g:381:9: 'nothing_will_match_this_dedent'
			{
			DebugLocation(381, 9);
			Match("nothing_will_match_this_dedent"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DEDENT", 31);
			LeaveRule("DEDENT", 31);
			LeaveRule_DEDENT();
		}
	}
	// $ANTLR end "DEDENT"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 32);
		TraceIn("WS", 32);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// Stone.g:383:3: ( ' ' )
			DebugEnterAlt(1);
			// Stone.g:383:5: ' '
			{
			DebugLocation(383, 5);
			Match(' '); 
			DebugLocation(383, 9);
			 Skip(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 32);
			LeaveRule("WS", 32);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	public override void mTokens()
	{
		// Stone.g:1:8: ( Expr_Access | OP_DIV | OP_MINUS | OP_MUL | OP_PLUS | T__51 | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | T__59 | T__60 | T__61 | T__62 | T__63 | T__64 | T__65 | T__66 | T__67 | NEWLINE | LIDENT | UIDENT | NORMAL_STRING | INT | DOUBLE | INDENT | DEDENT | WS )
		int alt24=31;
		try { DebugEnterDecision(24, false);
		try
		{
			alt24 = dfa24.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(24); }
		switch (alt24)
		{
		case 1:
			DebugEnterAlt(1);
			// Stone.g:1:10: Expr_Access
			{
			DebugLocation(1, 10);
			mExpr_Access(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// Stone.g:1:22: OP_DIV
			{
			DebugLocation(1, 22);
			mOP_DIV(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// Stone.g:1:29: OP_MINUS
			{
			DebugLocation(1, 29);
			mOP_MINUS(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// Stone.g:1:38: OP_MUL
			{
			DebugLocation(1, 38);
			mOP_MUL(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// Stone.g:1:45: OP_PLUS
			{
			DebugLocation(1, 45);
			mOP_PLUS(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// Stone.g:1:53: T__51
			{
			DebugLocation(1, 53);
			mT__51(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// Stone.g:1:59: T__52
			{
			DebugLocation(1, 59);
			mT__52(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// Stone.g:1:65: T__53
			{
			DebugLocation(1, 65);
			mT__53(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// Stone.g:1:71: T__54
			{
			DebugLocation(1, 71);
			mT__54(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// Stone.g:1:77: T__55
			{
			DebugLocation(1, 77);
			mT__55(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// Stone.g:1:83: T__56
			{
			DebugLocation(1, 83);
			mT__56(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// Stone.g:1:89: T__57
			{
			DebugLocation(1, 89);
			mT__57(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// Stone.g:1:95: T__58
			{
			DebugLocation(1, 95);
			mT__58(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// Stone.g:1:101: T__59
			{
			DebugLocation(1, 101);
			mT__59(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// Stone.g:1:107: T__60
			{
			DebugLocation(1, 107);
			mT__60(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// Stone.g:1:113: T__61
			{
			DebugLocation(1, 113);
			mT__61(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// Stone.g:1:119: T__62
			{
			DebugLocation(1, 119);
			mT__62(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// Stone.g:1:125: T__63
			{
			DebugLocation(1, 125);
			mT__63(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// Stone.g:1:131: T__64
			{
			DebugLocation(1, 131);
			mT__64(); 

			}
			break;
		case 20:
			DebugEnterAlt(20);
			// Stone.g:1:137: T__65
			{
			DebugLocation(1, 137);
			mT__65(); 

			}
			break;
		case 21:
			DebugEnterAlt(21);
			// Stone.g:1:143: T__66
			{
			DebugLocation(1, 143);
			mT__66(); 

			}
			break;
		case 22:
			DebugEnterAlt(22);
			// Stone.g:1:149: T__67
			{
			DebugLocation(1, 149);
			mT__67(); 

			}
			break;
		case 23:
			DebugEnterAlt(23);
			// Stone.g:1:155: NEWLINE
			{
			DebugLocation(1, 155);
			mNEWLINE(); 

			}
			break;
		case 24:
			DebugEnterAlt(24);
			// Stone.g:1:163: LIDENT
			{
			DebugLocation(1, 163);
			mLIDENT(); 

			}
			break;
		case 25:
			DebugEnterAlt(25);
			// Stone.g:1:170: UIDENT
			{
			DebugLocation(1, 170);
			mUIDENT(); 

			}
			break;
		case 26:
			DebugEnterAlt(26);
			// Stone.g:1:177: NORMAL_STRING
			{
			DebugLocation(1, 177);
			mNORMAL_STRING(); 

			}
			break;
		case 27:
			DebugEnterAlt(27);
			// Stone.g:1:191: INT
			{
			DebugLocation(1, 191);
			mINT(); 

			}
			break;
		case 28:
			DebugEnterAlt(28);
			// Stone.g:1:195: DOUBLE
			{
			DebugLocation(1, 195);
			mDOUBLE(); 

			}
			break;
		case 29:
			DebugEnterAlt(29);
			// Stone.g:1:202: INDENT
			{
			DebugLocation(1, 202);
			mINDENT(); 

			}
			break;
		case 30:
			DebugEnterAlt(30);
			// Stone.g:1:209: DEDENT
			{
			DebugLocation(1, 209);
			mDEDENT(); 

			}
			break;
		case 31:
			DebugEnterAlt(31);
			// Stone.g:1:216: WS
			{
			DebugLocation(1, 216);
			mWS(); 

			}
			break;

		}

	}


	#region DFA
	DFA8 dfa8;
	DFA21 dfa21;
	DFA24 dfa24;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa8 = new DFA8(this);
		dfa21 = new DFA21(this);
		dfa24 = new DFA24(this);
	}

	private class DFA8 : DFA
	{
		private const string DFA8_eotS =
			"\x1\xFFFF\x2\x3\x2\xFFFF";
		private const string DFA8_eofS =
			"\x5\xFFFF";
		private const string DFA8_minS =
			"\x1\x41\x2\x2E\x2\xFFFF";
		private const string DFA8_maxS =
			"\x1\x5A\x2\x7A\x2\xFFFF";
		private const string DFA8_acceptS =
			"\x3\xFFFF\x1\x2\x1\x1";
		private const string DFA8_specialS =
			"\x5\xFFFF}>";
		private static readonly string[] DFA8_transitionS =
			{
				"\x1A\x1",
				"\x1\x4\x12\xFFFF\x1A\x2\x6\xFFFF\x1A\x2",
				"\x1\x4\x12\xFFFF\x1A\x2\x6\xFFFF\x1A\x2",
				"",
				""
			};

		private static readonly short[] DFA8_eot = DFA.UnpackEncodedString(DFA8_eotS);
		private static readonly short[] DFA8_eof = DFA.UnpackEncodedString(DFA8_eofS);
		private static readonly char[] DFA8_min = DFA.UnpackEncodedStringToUnsignedChars(DFA8_minS);
		private static readonly char[] DFA8_max = DFA.UnpackEncodedStringToUnsignedChars(DFA8_maxS);
		private static readonly short[] DFA8_accept = DFA.UnpackEncodedString(DFA8_acceptS);
		private static readonly short[] DFA8_special = DFA.UnpackEncodedString(DFA8_specialS);
		private static readonly short[][] DFA8_transition;

		static DFA8()
		{
			int numStates = DFA8_transitionS.Length;
			DFA8_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA8_transition[i] = DFA.UnpackEncodedString(DFA8_transitionS[i]);
			}
		}

		public DFA8( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 8;
			this.eot = DFA8_eot;
			this.eof = DFA8_eof;
			this.min = DFA8_min;
			this.max = DFA8_max;
			this.accept = DFA8_accept;
			this.special = DFA8_special;
			this.transition = DFA8_transition;
		}

		public override string Description { get { return "()* loopback of 356:9: ( ( 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' )* '.' )*"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA21 : DFA
	{
		private const string DFA21_eotS =
			"\x5\xFFFF";
		private const string DFA21_eofS =
			"\x5\xFFFF";
		private const string DFA21_minS =
			"\x2\x2E\x3\xFFFF";
		private const string DFA21_maxS =
			"\x1\x39\x1\x65\x3\xFFFF";
		private const string DFA21_acceptS =
			"\x2\xFFFF\x1\x2\x1\x1\x1\x3";
		private const string DFA21_specialS =
			"\x5\xFFFF}>";
		private static readonly string[] DFA21_transitionS =
			{
				"\x1\x2\x1\xFFFF\xA\x1",
				"\x1\x3\x1\xFFFF\xA\x1\xB\xFFFF\x1\x4\x1F\xFFFF\x1\x4",
				"",
				"",
				""
			};

		private static readonly short[] DFA21_eot = DFA.UnpackEncodedString(DFA21_eotS);
		private static readonly short[] DFA21_eof = DFA.UnpackEncodedString(DFA21_eofS);
		private static readonly char[] DFA21_min = DFA.UnpackEncodedStringToUnsignedChars(DFA21_minS);
		private static readonly char[] DFA21_max = DFA.UnpackEncodedStringToUnsignedChars(DFA21_maxS);
		private static readonly short[] DFA21_accept = DFA.UnpackEncodedString(DFA21_acceptS);
		private static readonly short[] DFA21_special = DFA.UnpackEncodedString(DFA21_specialS);
		private static readonly short[][] DFA21_transition;

		static DFA21()
		{
			int numStates = DFA21_transitionS.Length;
			DFA21_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA21_transition[i] = DFA.UnpackEncodedString(DFA21_transitionS[i]);
			}
		}

		public DFA21( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 21;
			this.eot = DFA21_eot;
			this.eof = DFA21_eof;
			this.min = DFA21_min;
			this.max = DFA21_max;
			this.accept = DFA21_accept;
			this.special = DFA21_special;
			this.transition = DFA21_transition;
		}

		public override string Description { get { return "368:1: DOUBLE : ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA24 : DFA
	{
		private const string DFA24_eotS =
			"\x1\xFFFF\x1\x1B\x1\xFFFF\x1\x1E\x5\xFFFF\x1\x20\x1\x22\x6\x19\x4\xFFFF"+
			"\x1\x2B\x1\x19\x1\xFFFF\x1\x2D\xA\xFFFF\x2\x19\x1\x30\x3\x19\x1\x2B\x2"+
			"\xFFFF\x1\x19\x1\xFFFF\x2\x19\x1\xFFFF\x5\x19\x1\x3C\x4\x19\x1\x41\x1"+
			"\xFFFF\x1\x19\x1\x43\x2\x19\x1\xFFFF\x1\x46\x1\xFFFF\x1\x47\x1\x19\x2"+
			"\xFFFF\x1\x19\x13\xFFFF";
		private const string DFA24_eofS =
			"\x5C\xFFFF";
		private const string DFA24_minS =
			"\x1\xA\x1\x30\x1\xFFFF\x1\x3E\x5\xFFFF\x1\x3A\x1\x3E\x1\x6C\x1\x61\x1"+
			"\x66\x1\x6F\x1\x72\x1\x65\x4\xFFFF\x1\x2E\x1\x6F\x1\xFFFF\x1\x2E\xA\xFFFF"+
			"\x1\x61\x1\x74\x1\x30\x1\x64\x1\x6F\x1\x74\x1\x2E\x1\x41\x1\xFFFF\x1"+
			"\x74\x1\xFFFF\x1\x73\x1\x61\x1\xFFFF\x1\x75\x1\x78\x1\x75\x1\x68\x1\x73"+
			"\x1\x30\x1\x6C\x1\x79\x1\x72\x1\x69\x1\x30\x1\xFFFF\x1\x65\x1\x30\x2"+
			"\x6E\x1\xFFFF\x1\x30\x1\xFFFF\x1\x30\x1\x67\x2\xFFFF\x1\x5F\x1\x77\x1"+
			"\x69\x2\x6C\x1\x5F\x1\x6D\x1\x61\x1\x74\x1\x63\x1\x68\x1\x5F\x1\x74\x1"+
			"\x68\x1\x69\x1\x73\x1\x5F\x1\x64\x2\xFFFF";
		private const string DFA24_maxS =
			"\x1\x3BB\x1\x39\x1\xFFFF\x1\x3E\x5\xFFFF\x1\x3A\x1\x3E\x1\x6C\x1\x61"+
			"\x1\x66\x1\x6F\x1\x72\x1\x65\x4\xFFFF\x1\x7A\x1\x6F\x1\xFFFF\x1\x65\xA"+
			"\xFFFF\x1\x61\x1\x74\x1\x7A\x1\x64\x1\x6F\x1\x74\x2\x7A\x1\xFFFF\x1\x74"+
			"\x1\xFFFF\x1\x73\x1\x61\x1\xFFFF\x1\x75\x1\x78\x1\x75\x1\x68\x1\x73\x1"+
			"\x7A\x1\x6C\x1\x79\x1\x72\x1\x69\x1\x7A\x1\xFFFF\x1\x65\x1\x7A\x2\x6E"+
			"\x1\xFFFF\x1\x7A\x1\xFFFF\x1\x7A\x1\x67\x2\xFFFF\x1\x5F\x1\x77\x1\x69"+
			"\x2\x6C\x1\x5F\x1\x6D\x1\x61\x1\x74\x1\x63\x1\x68\x1\x5F\x1\x74\x1\x68"+
			"\x1\x69\x1\x73\x1\x5F\x1\x69\x2\xFFFF";
		private const string DFA24_acceptS =
			"\x2\xFFFF\x1\x2\x1\xFFFF\x1\x4\x1\x5\x1\x6\x1\x7\x1\x8\x8\xFFFF\x1\x14"+
			"\x1\x15\x1\x16\x1\x17\x2\xFFFF\x1\x1A\x1\xFFFF\x1\x18\x1\x1F\x1\x1\x1"+
			"\x1C\x1\x9\x1\x3\x1\xB\x1\xA\x1\xD\x1\xC\x8\xFFFF\x1\x19\x1\xFFFF\x1"+
			"\x1B\x2\xFFFF\x1\x10\xB\xFFFF\x1\xF\x4\xFFFF\x1\xE\x1\xFFFF\x1\x12\x2"+
			"\xFFFF\x1\x11\x1\x13\x12\xFFFF\x1\x1D\x1\x1E";
		private const string DFA24_specialS =
			"\x5C\xFFFF}>";
		private static readonly string[] DFA24_transitionS =
			{
				"\x1\x14\x15\xFFFF\x1\x1A\x1\xFFFF\x1\x17\x4\xFFFF\x1\x17\x1\x6\x1\x7"+
				"\x1\x4\x1\x5\x1\x8\x1\x3\x1\x1\x1\x2\xA\x18\x1\x9\x2\xFFFF\x1\xA\x3"+
				"\xFFFF\x1A\x15\x6\xFFFF\x2\x19\x1\xB\x1\xC\x4\x19\x1\xD\x3\x19\x1\xE"+
				"\x1\x16\x1\x19\x1\xF\x1\x19\x1\x10\x8\x19\x1\xFFFF\x1\x11\x5A\xFFFF"+
				"\x1\x12\x2E3\xFFFF\x1\x13",
				"\xA\x1C",
				"",
				"\x1\x1D",
				"",
				"",
				"",
				"",
				"",
				"\x1\x1F",
				"\x1\x21",
				"\x1\x23",
				"\x1\x24",
				"\x1\x25",
				"\x1\x26",
				"\x1\x27",
				"\x1\x28",
				"",
				"",
				"",
				"",
				"\x1\x2A\x12\xFFFF\x1A\x29\x6\xFFFF\x1A\x29",
				"\x1\x2C",
				"",
				"\x1\x1C\x1\xFFFF\xA\x18\xB\xFFFF\x1\x1C\x1F\xFFFF\x1\x1C",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x2E",
				"\x1\x2F",
				"\xA\x19\x7\xFFFF\x1A\x19\x6\xFFFF\x1A\x19",
				"\x1\x31",
				"\x1\x32",
				"\x1\x33",
				"\x1\x2A\x12\xFFFF\x1A\x29\x6\xFFFF\x1A\x29",
				"\x1A\x15\x6\xFFFF\x1A\x19",
				"",
				"\x1\x34",
				"",
				"\x1\x35",
				"\x1\x36",
				"",
				"\x1\x37",
				"\x1\x38",
				"\x1\x39",
				"\x1\x3A",
				"\x1\x3B",
				"\xA\x19\x7\xFFFF\x1A\x19\x6\xFFFF\x1A\x19",
				"\x1\x3D",
				"\x1\x3E",
				"\x1\x3F",
				"\x1\x40",
				"\xA\x19\x7\xFFFF\x1A\x19\x6\xFFFF\x1A\x19",
				"",
				"\x1\x42",
				"\xA\x19\x7\xFFFF\x1A\x19\x6\xFFFF\x1A\x19",
				"\x1\x44",
				"\x1\x45",
				"",
				"\xA\x19\x7\xFFFF\x1A\x19\x6\xFFFF\x1A\x19",
				"",
				"\xA\x19\x7\xFFFF\x1A\x19\x6\xFFFF\x1A\x19",
				"\x1\x48",
				"",
				"",
				"\x1\x49",
				"\x1\x4A",
				"\x1\x4B",
				"\x1\x4C",
				"\x1\x4D",
				"\x1\x4E",
				"\x1\x4F",
				"\x1\x50",
				"\x1\x51",
				"\x1\x52",
				"\x1\x53",
				"\x1\x54",
				"\x1\x55",
				"\x1\x56",
				"\x1\x57",
				"\x1\x58",
				"\x1\x59",
				"\x1\x5B\x4\xFFFF\x1\x5A",
				"",
				""
			};

		private static readonly short[] DFA24_eot = DFA.UnpackEncodedString(DFA24_eotS);
		private static readonly short[] DFA24_eof = DFA.UnpackEncodedString(DFA24_eofS);
		private static readonly char[] DFA24_min = DFA.UnpackEncodedStringToUnsignedChars(DFA24_minS);
		private static readonly char[] DFA24_max = DFA.UnpackEncodedStringToUnsignedChars(DFA24_maxS);
		private static readonly short[] DFA24_accept = DFA.UnpackEncodedString(DFA24_acceptS);
		private static readonly short[] DFA24_special = DFA.UnpackEncodedString(DFA24_specialS);
		private static readonly short[][] DFA24_transition;

		static DFA24()
		{
			int numStates = DFA24_transitionS.Length;
			DFA24_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA24_transition[i] = DFA.UnpackEncodedString(DFA24_transitionS[i]);
			}
		}

		public DFA24( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 24;
			this.eot = DFA24_eot;
			this.eof = DFA24_eof;
			this.min = DFA24_min;
			this.max = DFA24_max;
			this.accept = DFA24_accept;
			this.special = DFA24_special;
			this.transition = DFA24_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( Expr_Access | OP_DIV | OP_MINUS | OP_MUL | OP_PLUS | T__51 | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | T__59 | T__60 | T__61 | T__62 | T__63 | T__64 | T__65 | T__66 | T__67 | NEWLINE | LIDENT | UIDENT | NORMAL_STRING | INT | DOUBLE | INDENT | DEDENT | WS );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}

} // namespace  Stone.Compiler 
